import type { AccomplishmentDefinition } from "@course-mastery/schema";

/**
 * Structured form of ACCOMPLISHMENTS_PROPOSAL.md (repo root). STATUS:
 * PROPOSED, not yet signed off by the founder and not yet loaded by
 * tools/seed. MP values and tier placement are provisional
 * (PRODUCT_SPEC.md §20).
 *
 * Two entries (`personal-best-nine`, `bogey-free-nine`) collapse the
 * proposal's "front or back" language to a single front-nine instance —
 * the engine's `personal_best`/`absence` families need a concrete half.
 * Adding the back-nine counterpart later is a pure data change (another
 * row with half: "back"), not a design change.
 */
export const initialAccomplishments: AccomplishmentDefinition[] = [
  // Familiarity
  {
    slug: "first-round-played",
    version: 1,
    family: "round_count_milestone",
    tier: "familiarity",
    name: "First Round",
    description: "Complete your first round at this course.",
    mpValue: 25,
    params: { atCount: 1 },
    active: true,
  },
  {
    slug: "first-par",
    version: 1,
    family: "hole_relative_to_par",
    tier: "familiarity",
    name: "First Par",
    description: "Score par on any hole.",
    mpValue: 15,
    params: { relation: "par_or_better", scope: "any_hole" },
    active: true,
  },
  {
    slug: "first-birdie-or-better",
    version: 1,
    family: "hole_relative_to_par",
    tier: "familiarity",
    name: "First Birdie",
    description: "Score birdie or better on any hole.",
    mpValue: 30,
    params: { relation: "birdie_or_better", scope: "any_hole" },
    active: true,
  },
  {
    slug: "full-round-tracked",
    version: 1,
    family: "absence",
    tier: "familiarity",
    name: "Full Round Tracked",
    description: "Submit a round with every hole explicitly scored.",
    mpValue: 15,
    params: { scope: "full_round", maxAllowedRelativeToPar: null },
    active: true,
  },
  {
    slug: "front-nine-under-personal-threshold",
    version: 1,
    family: "nine_hole_threshold",
    tier: "familiarity",
    name: "Front Nine Pace",
    description: "Front nine score at or under a personalized pace threshold.",
    mpValue: 25,
    params: { half: "front" },
    active: true,
  },
  {
    slug: "back-nine-under-personal-threshold",
    version: 1,
    family: "nine_hole_threshold",
    tier: "familiarity",
    name: "Back Nine Pace",
    description: "Back nine score at or under a personalized pace threshold.",
    mpValue: 25,
    params: { half: "back" },
    active: true,
  },
  {
    slug: "three-rounds-played",
    version: 1,
    family: "round_count_milestone",
    tier: "familiarity",
    name: "Third Round",
    description: "Play your 3rd round at this course.",
    mpValue: 20,
    params: { atCount: 3 },
    active: true,
  },

  // Competence
  {
    slug: "two-pars-in-a-round",
    version: 1,
    family: "counts_within_round",
    tier: "competence",
    name: "Two Pars",
    description: "Score par or better on 2+ holes in one round.",
    mpValue: 20,
    params: { relation: "par_or_better", minCount: 2 },
    active: true,
  },
  {
    slug: "bogey-or-better-streak-3",
    version: 1,
    family: "streak_within_round",
    tier: "competence",
    name: "Three in a Row",
    description: "3 consecutive holes bogey-or-better.",
    mpValue: 30,
    params: { relation: "bogey_or_better", length: 3 },
    active: true,
  },
  {
    slug: "round-under-personal-threshold",
    version: 1,
    family: "round_score_threshold",
    tier: "competence",
    name: "Personal Pace",
    description: "Full round under a personalized score threshold.",
    mpValue: 40,
    params: {},
    active: true,
  },
  {
    slug: "no-blowup-holes",
    version: 1,
    family: "absence",
    tier: "competence",
    name: "No Blowups",
    description: "A complete round with no hole worse than double bogey.",
    mpValue: 35,
    params: { scope: "full_round", maxAllowedRelativeToPar: 2 },
    active: true,
  },
  {
    slug: "personal-best-round",
    version: 1,
    family: "personal_best",
    tier: "competence",
    name: "New Personal Best",
    description: "Lowest 18-hole score yet recorded at this course.",
    mpValue: 50,
    params: { scope: "round" },
    active: true,
  },
  {
    slug: "five-rounds-played",
    version: 1,
    family: "round_count_milestone",
    tier: "competence",
    name: "Fifth Round",
    description: "Play your 5th round at this course.",
    mpValue: 30,
    params: { atCount: 5 },
    active: true,
  },
  {
    slug: "tighter-than-last-five",
    version: 1,
    family: "compression",
    tier: "competence",
    name: "Finding Your Game",
    description: "This round lands closer to your recent average than any of your last 5 rounds did.",
    mpValue: 30,
    params: { comparisonWindow: 5 },
    active: true,
  },

  // Command
  {
    slug: "four-pars-in-a-round",
    version: 1,
    family: "counts_within_round",
    tier: "command",
    name: "Four Pars",
    description: "Score par or better on 4+ holes in one round.",
    mpValue: 35,
    params: { relation: "par_or_better", minCount: 4 },
    active: true,
  },
  {
    slug: "bogey-or-better-streak-6",
    version: 1,
    family: "streak_within_round",
    tier: "command",
    name: "Six in a Row",
    description: "6 consecutive holes bogey-or-better.",
    mpValue: 50,
    params: { relation: "bogey_or_better", length: 6 },
    active: true,
  },
  {
    slug: "personal-best-nine",
    version: 1,
    family: "personal_best",
    tier: "command",
    name: "New Nine Best",
    description: "Lowest 9-hole (front) score yet recorded at this course.",
    mpValue: 35,
    params: { scope: "nine", half: "front" },
    active: true,
  },
  {
    slug: "consistency-window-3",
    version: 1,
    family: "consistency_recent_rounds",
    tier: "command",
    name: "Finding a Groove",
    description: "Your last 3 rounds at this course all land within a personalized stroke band.",
    mpValue: 45,
    params: { windowSize: 3 },
    active: true,
  },
  {
    slug: "ten-rounds-played",
    version: 1,
    family: "round_count_milestone",
    tier: "command",
    name: "Tenth Round",
    description: "Play your 10th round at this course.",
    mpValue: 40,
    params: { atCount: 10 },
    active: true,
  },
  {
    slug: "bogey-free-nine",
    version: 1,
    family: "absence",
    tier: "command",
    name: "Bogey-Free Nine",
    description: "A complete 9 holes (front) with no hole worse than bogey.",
    mpValue: 60,
    params: { scope: "nine", half: "front", maxAllowedRelativeToPar: 1 },
    active: true,
  },
];
